In [1]:
import numpy as np

myarray = np.array([[1,2,3], \
        [4,5,6], \
        [7,8,9], \
        [10,11,12]])
print(myarray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
myarray.mean(axis=0)

array([5.5, 6.5, 7.5])

In [3]:
myarray.mean(axis=1)

array([ 2.,  5.,  8., 11.])